package org.agrosoft.BasicSpringCrud.enums;

public enum NivelEscolaridadEnum {
	SIN_ESTUDIOS,
	PRIMARIA_TRUNCA,
	PRIMARIA_TERMINADA,
	SECUNDARIA_TRUNCA,
	SECUNDARIA_TERMINADA,
	PREPARATORIA_TRUNCA,
	PREPARATORIA_TERMINADA,
	UNIVERSIDAD_TRUNCA,
	UNIVERSIDAD_TERMINADA,
	POSTGRADO
}
